baseURL = "https://vimkim.github.io/"
languageCode = "ko-kr"
title = "vimkim's study blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "vimkim's Study Blog"
  description = "Live as if you were to die tomorrow. Learn as if you were to live forever."
  github = "vimkim"
  # facebook = "MeiK2333"
  # twitter = "MeiK2333"
  # linkedin = "MeiK2333"
  # instagram = "MeiK2333"
  # tumblr = "MeiK2333"
  email = "kimdhyungg@gmail.com"
  url = "https://vimkim.github.io"
  keywords = "blog, google analytics"
  # rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "https://vimkim.github.io/images/vim.png"
  avatar = "https://vimkim.github.io/images/vim.png"
  headerIcon = "https://vimkim.github.io/studyblog/images/github-mark-white.png"
  # headerIcon = "https://vimkim.github.io/images/vim.png"
  location = "South Korea"
  enableGitalk = true

  [params.gitalk]
    clientID = "f107517b590c78bb2397"
    clientSecret = "1dd7a404b2b46a7b7150c69ec11eef3c157ddd50"
    repo = "studyblog"
    owner = "vimkim"
    admin = "vimkim"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  #[[params.links]]
  #  title = "Link"
  #  href = "https://github.com/vimkim"
  [[params.links]]
    title = "Link2"
    href = "https://vimkim.github.io"
    icon = "https://vimkim.github.io/images/vim.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    # ID = "UA-123456-789"